name: chat_demo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  flutter_markdown: ^0.7.1
  highlight: ^0.7.0
  shimmer: ^3.0.0
  url_launcher: ^6.3.0
  markdown: 7.3.0
  flutter_animate:
  flutter_svg:

dependency_overrides:
  characters: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # 👇 Add your assets folder(s) here
  assets:
    - assets/logo.svg

